export const CHANGE_SEARCH_SONGS_RES = "search/CHANGE_SEARCH_SONGS_RES";
export const CHANGE_KEYWORDS = "search/CHANGE_KEYWORDS";
export const CHANGE_TYPE = "search/CHANGE_TYPE";
export const CHANGE_SEARCH_ARTISTS_RES = "search/CHANGE_SEARCH_ARTISTS_RES";
export const CHANGE_SEARCH_ALBUMS_RES = "search/CHANGE_SEARCH_ALBUMS_RES";
export const CHANGE_SEARCH_VIDEO_RES = "search/CHANGE_SEARCH_VIDEO_RES";
export const CHANGE_SEARCH_LYRIC_RES = "search/CHANGE_SEARCH_LYRIC_RES";
export const CHANGE_SEARCH_PLAYLIST_RES = "search/CHANGE_SEARCH_PLAYLIST_RES"